import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import "./globals.scss";
import { Footer, Header } from "@/components";
import { ReduxProvider } from "@/components/ReduxProvider";
import "@splidejs/splide/dist/css/themes/splide-default.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  setRequestLocale(locale);
  const messages = await getMessages();

  try {
    await getMessages();
  } catch (error) {
    notFound();
  }

  return (
    <ReduxProvider>
      <NextIntlClientProvider messages={messages}>
        <html lang={locale}>
          <body>
            <Header language={locale} />
            {children}
            <Footer />
          </body>
        </html>
      </NextIntlClientProvider>
    </ReduxProvider>
  );
}
